name: ci

on: push

jobs:
  build:
    runs-on: actuated-4cpu-4gb
    steps:
      - uses: actions/checkout@v3
        with:
          repository: "alexellis/registry-creds"
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: ~1.21
      - name: Setup Golang caches
        uses: tespkg/actions-cache@v1
        with:
          endpoint: "192.168.128.1"
          port: 8333
          insecure: true
          accessKey: ${{ secrets.ACTIONS_CACHE_ACCESS_KEY }}
          secretKey: ${{ secrets.ACTIONS_CACHE_SECRET_KEY }}
          bucket: actuated-runners
          use-fallback: true
          region: local
        
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-
      - name: Build
        run: |
          CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} \
          GO111MODULE=on go build -ldflags "-s -w -X main.Release=dev -X main.SHA=dev" -o controller
